import './globals.scss';
import type { Metadata } from 'next';
import { Providers } from '@/app/store/provider';
import Header from '@/app/components/Header/Header';

export const metadata: Metadata = {
  title: 'Wine cellar',
  description: 'Generated by create next app',
};
// корневое расположение, чтобы везде были html и body
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="body">
        <Providers>
          <Header/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
