import './globals.scss';
import type { Metadata } from 'next';
import { Providers } from '@/app/store/provider';
import Header from '@/app/components/Header/Header';
// import { Playfair_Display } from 'next/font/google';
// import { Montserrat } from 'next/font/google';

// export const playfairDisplay = Playfair_Display({
//   subsets: ['cyrillic','latin'],
//   weight: ['400', '500', '600', '700', '800', '900'],
//   style: ['italic', 'normal'],
// })
// export const montserrat = Montserrat({ 
//   subsets: ['cyrillic','latin'],
//   weight: ['400', '500', '600', '700', '800', '900'],
//   style: ['italic', 'normal'],
// })

export const metadata: Metadata = {
  title: 'Wine cellar',
  description: 'Generated by create next app',
};
// console.log(playfairDisplay.style);

// корневое расположение, чтобы везде были html и body
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='body'>
        <Providers>
          <Header/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
