import { optionsWineType } from "../types/wine.type";

export const optionsGrapeVariety: optionsWineType[] = [
  { value: "Абруско", label: "Абруско", name: "grapeVariety" },
  { value: "Агат Донской", label: "Агат Донской", name: "grapeVariety" },
  { value: "Агиоргитико", label: "Агиоргитико", name: "grapeVariety" },
  { value: "Алеатико", label: "Алеатико", name: "grapeVariety" },
  {
    value: "Александроули",
    label: "Александроули",
    name: "grapeVariety",
  },
  { value: "Алиберне", label: "Алиберне", name: "grapeVariety" },
  { value: "Аликант Буше", label: "Аликант Буше", name: "grapeVariety" },
  { value: "Алый терский", label: "Алый терский", name: "grapeVariety" },
  { value: "Альфа", label: "Альфа", name: "grapeVariety" },
  { value: "Альянико", label: "Альянико", name: "grapeVariety" },
  { value: "Андре", label: "Андре", name: "grapeVariety" },
  { value: "Анчелотта", label: "Анчелотта", name: "grapeVariety" },
  { value: "Аргаман", label: "Аргаман", name: "grapeVariety" },
  { value: "Бабич", label: "Бабич", name: "grapeVariety" },
  { value: "Барбера", label: "Барбера", name: "grapeVariety" },
  { value: "Бастардо", label: "Бастардо", name: "grapeVariety" },
  {
    value: "Бастардо Магарачский",
    label: "Бастардо Магарачский",
    name: "grapeVariety",
  },
  {
    value: "Виноград 'Башкирский Ранний'",
    label: "Виноград 'Башкирский Ранний'",
    name: "grapeVariety",
  },
  { value: "Блауфранкиш", label: "Блауфранкиш", name: "grapeVariety" },
  { value: "Бобаль", label: "Бобаль", name: "grapeVariety" },
  {
    value: "Виноград круглолистный",
    label: "Виноград круглолистный",
    name: "grapeVariety",
  },
  { value: "Вранац", label: "Вранац", name: "grapeVariety" },
  { value: "Гаме", label: "Гаме", name: "grapeVariety" },
  { value: "Гренаш", label: "Гренаш", name: "grapeVariety" },
  { value: "Добричич", label: "Добричич", name: "grapeVariety" },
  { value: "Дольчетто", label: "Дольчетто", name: "grapeVariety" },
  { value: "Дорнфельдер", label: "Дорнфельдер", name: "grapeVariety" },
  { value: "Дюриф", label: "Дюриф", name: "grapeVariety" },
  { value: "Заря севера", label: "Заря севера", name: "grapeVariety" },
  { value: "Зинфандель", label: "Зинфандель", name: "grapeVariety" },
  { value: "Изабелла", label: "Изабелла", name: "grapeVariety" },
  {
    value: "Каберне Моравия",
    label: "Каберне Моравия",
    name: "grapeVariety",
  },
  {
    value: "Каберне-совиньон",
    label: "Каберне-совиньон",
    name: "grapeVariety",
  },
  { value: "Каберне-фран", label: "Каберне-фран", name: "grapeVariety" },
  { value: "Кадарка", label: "Кадарка", name: "grapeVariety" },
  { value: "Канайоло", label: "Канайоло", name: "grapeVariety" },
  { value: "Кардинал", label: "Кардинал", name: "grapeVariety" },
  { value: "Кариньян", label: "Кариньян", name: "grapeVariety" },
  { value: "Карменер", label: "Карменер", name: "grapeVariety" },
  { value: "Кефесия", label: "Кефесия", name: "grapeVariety" },
  { value: "Конкорд", label: "Конкорд", name: "grapeVariety" },
  { value: "Корвина", label: "Корвина", name: "grapeVariety" },
  { value: "Коцифали", label: "Коцифали", name: "grapeVariety" },
  {
    value: "Красностоп золотовский",
    label: "Красностоп золотовский",
    name: "grapeVariety",
  },
  { value: "Ксиномавро", label: "Ксиномавро", name: "grapeVariety" },
  { value: "Лагрейн", label: "Лагрейн", name: "grapeVariety" },
  { value: "Ламбруско", label: "Ламбруско", name: "grapeVariety" },
  { value: "Листан Негро", label: "Листан Негро", name: "grapeVariety" },
  { value: "Мавро", label: "Мавро", name: "grapeVariety" },
  { value: "Мавродафни", label: "Мавродафни", name: "grapeVariety" },
  { value: "Мавруд", label: "Мавруд", name: "grapeVariety" },
  { value: "Мадраса", label: "Мадраса", name: "grapeVariety" },
  { value: "Мальбек", label: "Мальбек", name: "grapeVariety" },
  { value: "Мандилария", label: "Мандилария", name: "grapeVariety" },
  { value: "Маратефтико", label: "Маратефтико", name: "grapeVariety" },
  { value: "Марселан", label: "Марселан", name: "grapeVariety" },
  { value: "Менсия", label: "Менсия", name: "grapeVariety" },
  { value: "Мерло", label: "Мерло", name: "grapeVariety" },
  {
    value: "Монтепульчано",
    label: "Монтепульчано",
    name: "grapeVariety",
  },
  { value: "Муджуретули", label: "Муджуретули", name: "grapeVariety" },
  { value: "Мурведр", label: "Мурведр", name: "grapeVariety" },
  { value: "Неббиоло", label: "Неббиоло", name: "grapeVariety" },
  { value: "Негроамаро", label: "Негроамаро", name: "grapeVariety" },
  { value: "Неро д’Авола", label: "Неро д’Авола", name: "grapeVariety" },
  { value: "Оджалеши", label: "Оджалеши", name: "grapeVariety" },
  { value: "Памид", label: "Памид", name: "grapeVariety" },
  { value: "Пино менье", label: "Пино менье", name: "grapeVariety" },
  { value: "Пино-нуар", label: "Пино-нуар", name: "grapeVariety" },
  { value: "Пинотаж", label: "Пинотаж", name: "grapeVariety" },
  { value: "Плавац Мали", label: "Плавац Мали", name: "grapeVariety" },
  { value: "Португизер", label: "Португизер", name: "grapeVariety" },
  { value: "Пти вердо", label: "Пти вердо", name: "grapeVariety" },
  {
    value: "Ранний Магарача",
    label: "Ранний Магарача",
    name: "grapeVariety",
  },
  { value: "Сагрантино", label: "Сагрантино", name: "grapeVariety" },
  { value: "Санджовезе", label: "Санджовезе", name: "grapeVariety" },
  { value: "Саперави", label: "Саперави", name: "grapeVariety" },
  {
    value: "Саперави северный",
    label: "Саперави северный",
    name: "grapeVariety",
  },
  { value: "Сен-Лоран", label: "Сен-Лоран", name: "grapeVariety" },
  { value: "Сенсо", label: "Сенсо", name: "grapeVariety" },
  { value: "Сент Кру", label: "Сент Кру", name: "grapeVariety" },
  {
    value: "Серексия чёрная",
    label: "Серексия чёрная",
    name: "grapeVariety",
  },
  { value: "Сира", label: "Сира", name: "grapeVariety" },
  { value: "Станушина", label: "Станушина", name: "grapeVariety" },
  { value: "Сузао", label: "Сузао", name: "grapeVariety" },
  { value: "Тавквери", label: "Тавквери", name: "grapeVariety" },
  { value: "Таёжный", label: "Таёжный", name: "grapeVariety" },
  { value: "Таннат", label: "Таннат", name: "grapeVariety" },
  { value: "Темпранильо", label: "Темпранильо", name: "grapeVariety" },
  { value: "Тинта Негра", label: "Тинта Негра", name: "grapeVariety" },
  { value: "Томкорд", label: "Томкорд", name: "grapeVariety" },
  {
    value: "Торига Насионал",
    label: "Торига Насионал",
    name: "grapeVariety",
  },
  { value: "Троллингер", label: "Троллингер", name: "grapeVariety" },
  { value: "Усахелаури", label: "Усахелаури", name: "grapeVariety" },
  {
    value: "Фетяска чёрная",
    label: "Фетяска чёрная",
    name: "grapeVariety",
  },
  { value: "Фраппато", label: "Фраппато", name: "grapeVariety" },
  { value: "Цвайгельт", label: "Цвайгельт", name: "grapeVariety" },
  {
    value: "Цимлянский чёрный",
    label: "Цимлянский чёрный",
    name: "grapeVariety",
  },
  { value: "Айрен", label: "Айрен", name: "grapeVariety" },
  { value: "Александр", label: "Александр", name: "grapeVariety" },
  { value: "Алиготе", label: "Алиготе", name: "grapeVariety" },
  { value: "Альбана", label: "Альбана", name: "grapeVariety" },
  { value: "Альбариньо", label: "Альбариньо", name: "grapeVariety" },
  { value: "Альбильо", label: "Альбильо", name: "grapeVariety" },
  { value: "Арбан", label: "Арбан", name: "grapeVariety" },
  { value: "Арнеис", label: "Арнеис", name: "grapeVariety" },
  { value: "Асиртико", label: "Асиртико", name: "grapeVariety" },
  { value: "Атири", label: "Атири", name: "grapeVariety" },
  { value: "Аурелиус", label: "Аурелиус", name: "grapeVariety" },
  { value: "Баяншира", label: "Баяншира", name: "grapeVariety" },
  { value: "Боал", label: "Боал", name: "grapeVariety" },
  { value: "Вельшрислинг", label: "Вельшрислинг", name: "grapeVariety" },
  { value: "Верделью", label: "Верделью", name: "grapeVariety" },
  { value: "Вердехо", label: "Вердехо", name: "grapeVariety" },
  { value: "Вердиккио", label: "Вердиккио", name: "grapeVariety" },
  { value: "Верментино", label: "Верментино", name: "grapeVariety" },
  { value: "Видаль-блан", label: "Видаль-блан", name: "grapeVariety" },
  { value: "Вионье", label: "Вионье", name: "grapeVariety" },
  { value: "Гарганега", label: "Гарганега", name: "grapeVariety" },
  {
    value: "Гевюрцтраминер",
    label: "Гевюрцтраминер",
    name: "grapeVariety",
  },
  { value: "Гибернал", label: "Гибернал", name: "grapeVariety" },
  { value: "Глера", label: "Глера", name: "grapeVariety" },
  {
    value: "Горули Мцване",
    label: "Горули Мцване",
    name: "grapeVariety",
  },
  { value: "Грекетто", label: "Грекетто", name: "grapeVariety" },
  {
    value: "Грюнер Вельтлинер",
    label: "Грюнер Вельтлинер",
    name: "grapeVariety",
  },
  { value: "Гуэ", label: "Гуэ", name: "grapeVariety" },
  { value: "Зета", label: "Зета", name: "grapeVariety" },
  { value: "Иршаи Оливер", label: "Иршаи Оливер", name: "grapeVariety" },
  { value: "Кернер", label: "Кернер", name: "grapeVariety" },
  { value: "Киси", label: "Киси", name: "grapeVariety" },
  { value: "Кишмиш белый", label: "Кишмиш белый", name: "grapeVariety" },
  { value: "Клерет белый", label: "Клерет белый", name: "grapeVariety" },
  { value: "Кокур белый", label: "Кокур белый", name: "grapeVariety" },
  { value: "Косю", label: "Косю", name: "grapeVariety" },
  { value: "Ксинистери", label: "Ксинистери", name: "grapeVariety" },
  { value: "Лидия", label: "Лидия", name: "grapeVariety" },
  { value: "Макабео", label: "Макабео", name: "grapeVariety" },
  { value: "Мальвазия", label: "Мальвазия", name: "grapeVariety" },
  { value: "Марсан", label: "Марсан", name: "grapeVariety" },
  { value: "Мускат белый", label: "Мускат белый", name: "grapeVariety" },
  {
    value: "Мускат моравский",
    label: "Мускат моравский",
    name: "grapeVariety",
  },
  { value: "Мцване", label: "Мцване", name: "grapeVariety" },
  {
    value: "Мюллер-Тургау",
    label: "Мюллер-Тургау",
    name: "grapeVariety",
  },
  { value: "Нарма", label: "Нарма", name: "grapeVariety" },
  { value: "Нойбургер", label: "Нойбургер", name: "grapeVariety" },
  { value: "Палава", label: "Палава", name: "grapeVariety" },
  { value: "Паломино", label: "Паломино", name: "grapeVariety" },
  { value: "Памид", label: "Памид", name: "grapeVariety" },
  {
    value: "Памяти Стреляевой",
    label: "Памяти Стреляевой",
    name: "grapeVariety",
  },
  { value: "Пассерина", label: "Пассерина", name: "grapeVariety" },
  {
    value: "Педро Хименес",
    label: "Педро Хименес",
    name: "grapeVariety",
  },
  { value: "Пекорино", label: "Пекорино", name: "grapeVariety" },
  { value: "Перле", label: "Перле", name: "grapeVariety" },
  { value: "Пино-блан", label: "Пино-блан", name: "grapeVariety" },
  { value: "Пино-гри", label: "Пино-гри", name: "grapeVariety" },
  { value: "Плавай", label: "Плавай", name: "grapeVariety" },
  { value: "Пошип", label: "Пошип", name: "grapeVariety" },
  {
    value: "Риболла джалла",
    label: "Риболла джалла",
    name: "grapeVariety",
  },
  {
    value: "Рилайнс Пинк Сидлис",
    label: "Рилайнс Пинк Сидлис",
    name: "grapeVariety",
  },
  { value: "Рислинг", label: "Рислинг", name: "grapeVariety" },
  { value: "Ркацители", label: "Ркацители", name: "grapeVariety" },
  {
    value: "Ротер Вельтлинер",
    label: "Ротер Вельтлинер",
    name: "grapeVariety",
  },
  { value: "Русан", label: "Русан", name: "grapeVariety" },
  { value: "Саваньен", label: "Саваньен", name: "grapeVariety" },
  { value: "Сары Пандас", label: "Сары Пандас", name: "grapeVariety" },
  { value: "Семильон", label: "Семильон", name: "grapeVariety" },
  { value: "Серсиаль", label: "Серсиаль", name: "grapeVariety" },
  { value: "Сибирьковый", label: "Сибирьковый", name: "grapeVariety" },
  { value: "Сильванер", label: "Сильванер", name: "grapeVariety" },
  { value: "Скуппернонг", label: "Скуппернонг", name: "grapeVariety" },
  {
    value: "Совиньон зелёный",
    label: "Совиньон зелёный",
    name: "grapeVariety",
  },
  {
    value: "Совиньон-блан",
    label: "Совиньон-блан",
    name: "grapeVariety",
  },
  { value: "Солярис", label: "Солярис", name: "grapeVariety" },
  { value: "Тельти Курук", label: "Тельти Курук", name: "grapeVariety" },
  { value: "Торронтес", label: "Торронтес", name: "grapeVariety" },
  { value: "Треббиано", label: "Треббиано", name: "grapeVariety" },
  { value: "Фетяска", label: "Фетяска", name: "grapeVariety" },
  {
    value: "Фетяска регала",
    label: "Фетяска регала",
    name: "grapeVariety",
  },
  {
    value: "Фрюротер Вельтлинер",
    label: "Фрюротер Вельтлинер",
    name: "grapeVariety",
  },
  { value: "Фурминт", label: "Фурминт", name: "grapeVariety" },
  { value: "Хихви", label: "Хихви", name: "grapeVariety" },
  { value: "Цереза", label: "Цереза", name: "grapeVariety" },
  { value: "Цоликоури", label: "Цоликоури", name: "grapeVariety" },
  { value: "Чауш", label: "Чауш", name: "grapeVariety" },
  { value: "Чинури", label: "Чинури", name: "grapeVariety" },
  { value: "Шаани белый", label: "Шаани белый", name: "grapeVariety" },
  { value: "Шардоне", label: "Шардоне", name: "grapeVariety" },
  { value: "Шенен", label: "Шенен", name: "grapeVariety" },
  { value: "Юбилейный", label: "Юбилейный", name: "grapeVariety" },
  {
    value: "Vitis Canadice",
    label: "Vitis Canadice",
    name: "grapeVariety",
  },
];
